# Test Local Module: Temporal_Module.TemporalDataFrame

In [1]:
import pandas as pd, numpy as np

In [2]:
import import_ipynb
import pandas as pd, numpy as np

In [3]:
from Temporal_Module import TemporalDataFrame

importing Jupyter notebook from Temporal_Module.ipynb


In [4]:
# Create dummy dataframe to test Feature_Ingestion Class

dummy_names = ['ID','A','B','C','D','Target']

dummy_values = [['Boris','Boris','Boris','Colton','Colton','Colton','Curtis','Curtis','Curtis'], 
                [1,5,3,4,5,6,7,7,4], [2,6,2,1,0,-1,6,7,2], 
                [3,7,7,8, 9, 10,8,6,7], [4,8,6,5,4,3,2,3,4],
               [0,1,0,1,0,1,0,1,0]]

dummy_df = pd.DataFrame(data = dummy_values).T
dummy_df.columns = dummy_names

dummy_df.head(9)

ID  A   B   C  D Target
0   Boris  1   2   3  4      0
1   Boris  5   6   7  8      1
2   Boris  3   2   7  6      0
3  Colton  4   1   8  5      1
4  Colton  5   0   9  4      0
5  Colton  6  -1  10  3      1
6  Curtis  7   6   8  2      0
7  Curtis  7   7   6  3      1
8  Curtis  4   2   7  4      0

In [5]:
dummy_df.columns.tolist()

['ID', 'A', 'B', 'C', 'D', 'Target']

### Intialize Class Instance

In [7]:
dummy_IF = TemporalDataFrame(dummy_df, lagged_obs = True)

3 time steps per member
3 unique members


In [8]:
print('Instance.col_names:', dummy_IF.col_names) # attributes
print()
print('Instance.feature_cols:', dummy_IF.feature_cols) 
print()
print('Instance.target_cols:', dummy_IF.target_cols)

Instance.col_names: ['ID', 'A', 'B', 'C', 'D', 'Target']

Instance.feature_cols: ['ID', 'A', 'B', 'C', 'D', 'Target']

Instance.target_cols: ['ID', 'Target']


In [9]:
print(dummy_IF.temporal_col_names( n_time_steps = 3, X_only = True, drop_ID = True))
print()
print(dummy_IF.temporal_col_names( n_time_steps = 3, y_only = True, drop_ID = False))

['A_0', 'B_0', 'C_0', 'D_0', 'Target_0', 'A_1', 'B_1', 'C_1', 'D_1', 'Target_1', 'A_2', 'B_2', 'C_2', 'D_2', 'Target_2']

['ID_0', 'Target_0', 'ID_1', 'Target_1', 'ID_2', 'Target_2']


### Long to Wide

In [10]:
dummy_IF.long_to_wide(X_only=True, show_ID=True)

ID  A_0  B_0  C_0  D_0  Target_0  A_1  B_1  C_1  D_1  Target_1  A_2  \
0   Boris    1    2    3    4         0    5    6    7    8         1    3   
1  Colton    4    1    8    5         1    5    0    9    4         0    6   
2  Curtis    7    6    8    2         0    7    7    6    3         1    4   

   B_2  C_2  D_2  Target_2  
0    2    7    6         0  
1   -1   10    3         1  
2    2    7    4         0

In [11]:
dummy_IF.long_to_wide(y_only = True, show_ID = True)

ID  Target_0  Target_1  Target_2
0   Boris         0         1         0
1  Colton         1         0         1
2  Curtis         0         1         0

### 3D Array

In [9]:
dummy_IF.X_3D()

#input_shape(n_time_steps, n_inputs)

6

In [22]:
dummy_IF.y_3D()

array([[[0],
        [1],
        [0]],

       [[1],
        [0],
        [1]],

       [[0],
        [1],
        [0]]], dtype=int64)

### Offset 

In [10]:
X,y = dummy_IF.offset(offset_by = 1)

In [11]:
X

A_0  B_0  C_0  D_0  A_1  B_1  C_1  D_1
0    1    2    3    4    5    6    7    8
1    4    1    8    5    5    0    9    4
2    7    6    8    2    7    7    6    3

In [25]:
y

Target_1  Target_2
0         1         0
1         0         1
2         1         0

## Offset 3D

In [26]:
X_,y_ = dummy_IF.offset_3D(offset_by = 1)

In [27]:
X_

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[4, 1, 8, 5],
        [5, 0, 9, 4]],

       [[7, 6, 8, 2],
        [7, 7, 6, 3]]], dtype=int64)

In [28]:
y_

array([[[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]]], dtype=int64)