# Test Custom Module

### temporal_module.Temporal_Data_Architect

In [1]:
import pandas as pd, numpy as np

In [2]:
import import_ipynb
from temporal_module import Temporal_Data_Architect

importing Jupyter notebook from temporal_module.ipynb


### Create dummy dataframe to test Feature_Ingestion Class

In [3]:
# Create dummy dataframe to test Feature_Ingestion Class

dummy_names = ['ID','A','B','C','D','Target']

dummy_values = [['Boris','Boris','Boris','Boris',
                 'Colton','Colton','Colton','Colton',
                 'Curtis','Curtis','Curtis','Curtis'], 
                [1,5,3,4,5,6,7,7,4,2,3,4], [2,6,2,1,0,-1,6,7,2,2,3,5], 
                [3,7,7,8, 9, 10,8,6,7,4,2,3], [4,8,6,5,4,3,2,3,4,1,2,3],
               [0,1,0,1,0,1,0,1,0,1,1,1]]

dummy_df = pd.DataFrame(data = dummy_values).T
dummy_df.columns = dummy_names

dummy_df.head(12)

ID  A   B   C  D Target
0    Boris  1   2   3  4      0
1    Boris  5   6   7  8      1
2    Boris  3   2   7  6      0
3    Boris  4   1   8  5      1
4   Colton  5   0   9  4      0
5   Colton  6  -1  10  3      1
6   Colton  7   6   8  2      0
7   Colton  7   7   6  3      1
8   Curtis  4   2   7  4      0
9   Curtis  2   2   4  1      1
10  Curtis  3   3   2  2      1
11  Curtis  4   5   3  3      1

In [4]:
dummy_df.columns.tolist()

['ID', 'A', 'B', 'C', 'D', 'Target']

### Intialize Class Instance

In [5]:
dummy_IF = Temporal_Data_Architect(dummy_df, lagged_obs = True)

4 time steps per member
3 unique members


### Print attributes

In [6]:
print('Instance.col_names:', dummy_IF.col_names) # attributes
print()
print('Instance.feature_cols:', dummy_IF.feature_cols) 
print()
print('Instance.target_cols:', dummy_IF.target_cols)

Instance.col_names: ['ID', 'A', 'B', 'C', 'D', 'Target']

Instance.feature_cols: ['ID', 'A', 'B', 'C', 'D', 'Target']

Instance.target_cols: ['ID', 'Target']


### Print column names for targets and features

In [7]:
print(dummy_IF.temporal_col_names( n_time_steps = 3, X_only = True, drop_ID = True))
print()
print(dummy_IF.temporal_col_names( n_time_steps = 3, y_only = True, drop_ID = False))

['A_0', 'B_0', 'C_0', 'D_0', 'Target_0', 'A_1', 'B_1', 'C_1', 'D_1', 'Target_1', 'A_2', 'B_2', 'C_2', 'D_2', 'Target_2']

['ID_0', 'Target_0', 'ID_1', 'Target_1', 'ID_2', 'Target_2']


### Long to Wide

In [8]:
dummy_IF.long_to_wide(X_only=True, show_ID=True)

ID  A_0  B_0  C_0  D_0  Target_0  A_1  B_1  C_1  D_1  ...  A_2  B_2  \
0   Boris    1    2    3    4         0    5    6    7    8  ...    3    2   
1  Colton    5    0    9    4         0    6   -1   10    3  ...    7    6   
2  Curtis    4    2    7    4         0    2    2    4    1  ...    3    3   

   C_2  D_2  Target_2  A_3  B_3  C_3  D_3  Target_3  
0    7    6         0    4    1    8    5         1  
1    8    2         0    7    7    6    3         1  
2    2    2         1    4    5    3    3         1  

[3 rows x 21 columns]

In [9]:
dummy_IF.long_to_wide(y_only = True, show_ID = True)

ID  Target_0  Target_1  Target_2  Target_3
0   Boris         0         1         0         1
1  Colton         0         1         0         1
2  Curtis         0         1         1         1

### 3D Array

In [10]:
dummy_IF.X_3D()

array([[[ 1,  2,  3,  4,  0],
        [ 5,  6,  7,  8,  1],
        [ 3,  2,  7,  6,  0],
        [ 4,  1,  8,  5,  1]],

       [[ 5,  0,  9,  4,  0],
        [ 6, -1, 10,  3,  1],
        [ 7,  6,  8,  2,  0],
        [ 7,  7,  6,  3,  1]],

       [[ 4,  2,  7,  4,  0],
        [ 2,  2,  4,  1,  1],
        [ 3,  3,  2,  2,  1],
        [ 4,  5,  3,  3,  1]]], dtype=int64)

In [11]:
dummy_IF.y_3D()

array([[[0],
        [1],
        [0],
        [1]],

       [[0],
        [1],
        [0],
        [1]],

       [[0],
        [1],
        [1],
        [1]]], dtype=int64)

### Offset 

In [12]:
X_2D,y_2D = dummy_IF.offset(offset_by = 1)

In [13]:
X_2D

A_0  B_0  C_0  D_0  Target_0  A_1  B_1  C_1  D_1  Target_1  A_2  B_2  C_2  \
0    1    2    3    4         0    5    6    7    8         1    3    2    7   
1    5    0    9    4         0    6   -1   10    3         1    7    6    8   
2    4    2    7    4         0    2    2    4    1         1    3    3    2   

   D_2  Target_2  
0    6         0  
1    2         0  
2    2         1

In [14]:
y_2D

Target_1  Target_2  Target_3
0         1         0         1
1         1         0         1
2         1         1         1

## Offset 3D

In [15]:
X_3D,y_3D = dummy_IF.offset_3D(offset_by = 1)
print("X shape is",X_3D.shape)
print()
print("y shape is",y_3D.shape)

X shape is (3, 3, 5)

y shape is (3, 3, 1)


In [16]:
X_3D

array([[[ 1,  2,  3,  4,  0],
        [ 5,  6,  7,  8,  1],
        [ 3,  2,  7,  6,  0]],

       [[ 5,  0,  9,  4,  0],
        [ 6, -1, 10,  3,  1],
        [ 7,  6,  8,  2,  0]],

       [[ 4,  2,  7,  4,  0],
        [ 2,  2,  4,  1,  1],
        [ 3,  3,  2,  2,  1]]], dtype=int64)

In [17]:
y_3D

array([[[1],
        [0],
        [1]],

       [[1],
        [0],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int64)

### Stretch Target

In [18]:
X_3D_stretch,y_3D_stretch = dummy_IF.offset_3D(offset_by = 1, input_stretch = 1)
print("X shape is now",X_3D_stretch.shape)
print()
print("y shape is now",y_3D_stretch.shape)

X shape is now (3, 2, 10)

y shape is now (3, 2, 1)


In [19]:
X_3D_stretch

array([[[1, 2, 3, 4, 0, 5, 6, 7, 8, 1],
        [5, 6, 7, 8, 1, 3, 2, 7, 6, 0]],

       [[5, 0, 9, 4, 0, 6, -1, 10, 3, 1],
        [6, -1, 10, 3, 1, 7, 6, 8, 2, 0]],

       [[4, 2, 7, 4, 0, 2, 2, 4, 1, 1],
        [2, 2, 4, 1, 1, 3, 3, 2, 2, 1]]], dtype=object)

In [20]:
y_3D_stretch

array([[[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [1]]], dtype=int64)